### ISSUE TITLE
documentation pr's also trigger vercel build just with a pregrabbed version of the website repo

### ISSUE THREAD

**Issue by hanbollar** [KittyCAD/documentation#26]

**Comment by jessfraz** [comment]
can we use this? https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration

**Comment by Irev-Dev** [comment]
I'm really not sure of an elegant solution here.
The ISR looks nice I butI don't really know how we'd use it. for example if we did something like the below, where we have a dev and a prod deployment, and the dev deployment gets it's data from whatever the most recent commit is across any branches, which might work if not a lot of people are making changes to the documentation, but problematic if two people put up a PR at the same time, whoever has the last commit even by a second will have their stuff displayed.
```typescript
export async function getStaticProps() {
  const getRes = () => {
    if(IS_PROD) {
      return fetch('https://lastest-documentation-main')
    } else {
      return fetch('https://lastest-documentation-commit-on-any-branch')
    }
  }
  const res = await getRes()
  const posts = await res.json()

  return {
    props: {
      posts,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 10, // In seconds
  }
}
```

Maybe if we go with Frank's Obsidian editing idea that will help fix it, because I'm not sure we really need git branches for documentation editing, might be fine to have a CMS type thing that always commits to the same branch? i.e. that would be `return fetch('https://lastest-commit-on-CMS-edit-branch')`

**Comment by jessfraz** [comment]
yeah that makes sense also i just realized this issue was for docs prs not like when main updates also update the website, because thats what ISR would be perfect for is just updating from main branch

**Comment by jessfraz** [comment]
i guess a question i have is do we really need to deploy the whole website for PRs here versus maybe using some sort of markdown linter to verify valid markdown?

**Comment by Irev-Dev** [comment]
I do like the idea of ISR for PRs because it's nice to sanity check what your edits look like and building the website does take a while. 

By markdown linter I'm guessing you're proposing that if the markdown is valid then just ship it without a sanity check, what does it look like on the website?
I can imagine that making me nervous depending on what's being done, like if there's tables, react components or images I'd like to see what it looks like.

**Comment by jessfraz** [comment]
yeah i took back that idea in my head after I realized they are all mdx and stuff could go very wrong

**Comment by jessfraz** [comment]
maybe if frank makes a design system we could use that here and then the sanity check could just be a way more minimalized rendering w the same design system idk, maybe obsidian is way easier than that as well haha

**Comment by jessfraz** [comment]
i think the hard part is the fact the website repo is private and this is public and if we just hooked vercel up to this repo with some open source design system voila, we get the previews on PRs for free

**Comment by jessfraz** [comment]
maybe im over thinking it lol ignore me we can have frank do what is best haha
